name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_php:
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [8.1]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Setup PHP 🏗
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies 👨🏻‍💻
        run: composer install --no-interaction --prefer-dist

      - name: Execute test code style 👀
        run: ./vendor/bin/pint --test -v
